<<<<<<< Updated upstream
lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
domain: tonysansone.me           # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://www.tonysansone.me  # the base hostname and protocol for your site, e.g. http://example.com
=======
lsi: false
safe: true
disable_disk_cache: true
profile: true
incremental: true
livereload: true

source: .
destination: ./_site
layouts_dir: ./_layouts
sass:
  sass_dir: ./assets/_sass

exclude: 
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


gist:
  noscript: false

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  parse_block_html: true
highlighter: rouge


>>>>>>> Stashed changes
