lsi: false
safe: true
disable_disk_cache: true
profile: true
incremental: true
livereload: true

source: .
destination: ./_site
layouts_dir: ./_layouts
sass:
  sass_dir: ./assets/_sass

exclude: 
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


gist:
  noscript: false

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  parse_block_html: true
highlighter: rouge
