lsi: false
safe: true
source: .
destination: ./_site
layouts_dir: _layouts
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  parse_block_html: true
livereload: true
sass:
  sass_dir: _assets/sass
  style: compressed
